### ISSUE TITLE
Map scroll back to top 

### ISSUE THREAD

**Issue by encontrethiago** [encontrethiago/trilha#1]
When leaving the popup window it should stay over the map, but its scrolling back to the top.

**Comment by gabrielAnglada** [comment]
Which browser are you using? In Chrome v69 cannot reproduce.

**Comment by encontrethiago** [comment]
Chrome 70.0.
Btw thanks for coming :) This issue in particular is solved by the anchors and some jQuery I managed to add. If you could look up at the whole structure and see if is everything correct and pro, it should be great my friend.
