### ISSUE TITLE
Pop up when "hide()" 

### ISSUE THREAD

**Issue by encontrethiago** [encontrethiago/trilha#9]
The pop up could act like fading "transition: all 5s ease-in-out;" but its not working, maybe there is sth on the jquery onclick="hide()"..

**Comment by mairamartinsk** [comment]
Fixed! jQuery's hide method was conflicting with the CSS transition, and also the 100 speed was way too fast (for instance one second is 1000). I passed "slow" (equals 600ms) as the argument.

Will send a PR with the fix.
